using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

/// <summary>
/// A button that shows a piece of PDA information and copies it to the clipboard when pressed.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PdaCopyButton : ContainerButton
{
    public bool TextVisible
    {
        get => TextLabel.Visible;
        set => TextLabel.Visible = value;
    }

    public PdaCopyButton()
    {
        RobustXamlLoader.Load(this);
        ToolTip = Loc.GetString("comp-pda-ui-copy-tooltip");
    }

    public void SetMarkup(string markup)
    {
        TextLabel.SetMarkup(markup);
    }
}
