#!/usr/bin/env python3
"""
Lidgren/RobustToolbox UDP packet sniffer for Space Station 14.

Parses the two-layer format:
  Layer 1 – Lidgren: [type:1][seq+frag:2][len_bits:2][payload:N] (5-byte header per chunk)
  Layer 2 – RobustToolbox: [msg_id:1][data...]  (after optional XChaCha20-Poly1305 decryption)

Encryption details (NetEncryption.cs):
  Algorithm : XChaCha20-Poly1305 (libsodium CryptoAeadXChaCha20Poly1305Ietf)
  Key       : 32-byte sharedSecret generated by client, sealed with server's X25519 pubkey
  Wire fmt  : [nonce_counter:uint64-LE 8B][xchacha20poly1305(ciphertext + 16B tag)]
  Nonces    : server starts at 0 +2 (even), client starts at 1 +2 (odd)

How to extract the session key (sharedSecret) on the client:
  Option 1 – source patch (recommended for dev):
    In RobustToolbox/Robust.Shared/Network/NetManager.ClientConnect.cs ~line 161,
    after RandomNumberGenerator.Fill(sharedSecret):
      _logger.Debug($"[KEYDUMP] {Convert.ToHexString(sharedSecret)}");

  Option 2 – patch NetEncryption constructor:
    In RobustToolbox/Robust.Shared/Network/NetEncryption.cs inside the ctor:
      Console.Error.WriteLine($"[KEYDUMP] {(isServer?"S":"C")} {Convert.ToHexString(key)}");

  Option 3 – dotnet-dump:
    dotnet-dump collect -p <PID>
    dotnet-dump analyze <dump>
    > dumpheap -type Robust.Shared.Network.NetEncryption
    > dumpobj <addr>   # read _key field

Usage:
  sudo python3 lidgren_udp_sniffer.py [--port 1212] [--iface lo] [--no-color]

Notes:
  - Requires raw socket access (run as root or with CAP_NET_RAW).
  - Post-handshake packets ARE encrypted by default (net.encrypt = true).
    To see decrypted payloads, start the server with `net.encrypt false`
    or pass the session key via --xchacha-key (64 hex chars = 32 bytes).
  - StringTable (msg_id 0) is always sent unencrypted during handshake,
    so the tool learns msg names automatically regardless of encryption.
"""

import argparse
import socket
import struct
import sys
import textwrap
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# ---------------------------------------------------------------------------
# Lidgren NetMessageType values (NetMessageType.cs)
# ---------------------------------------------------------------------------
NET_MSG_TYPES = {
    0:   "Unconnected",
    1:   "UserUnreliable",
    **{i: f"UserSequenced{i-1}"          for i in range(2, 34)},
    34:  "UserReliableUnordered",
    **{i: f"UserReliableSequenced{i-34}" for i in range(35, 67)},
    **{i: f"UserReliableOrdered{i-66}"   for i in range(67, 99)},
    129: "Ping",
    130: "Pong",
    131: "Connect",
    132: "ConnectResponse",
    133: "ConnectionEstablished",
    134: "Acknowledge",
    135: "Disconnect",
    136: "Discovery",
    137: "DiscoveryResponse",
    138: "NatPunchMessage",
    139: "NatIntroduction",
    140: "ExpandMTURequest",
    141: "ExpandMTUSuccess",
    142: "NatIntroductionConfirmRequest",
    143: "NatIntroductionConfirmed",
}

USER_DATA_TYPES = set(range(1, 99))  # types that carry application payload

# ANSI colours
C_RESET  = "\033[0m"
C_GRAY   = "\033[90m"
C_GREEN  = "\033[92m"
C_YELLOW = "\033[93m"
C_CYAN   = "\033[96m"
C_RED    = "\033[91m"
C_BOLD   = "\033[1m"

USE_COLOR = True


def col(c: str, s: str) -> str:
    return (c + s + C_RESET) if USE_COLOR else s


# ---------------------------------------------------------------------------
# Variable-length integer decoder (Lidgren zigzag LEB128)
# ---------------------------------------------------------------------------
def read_varuint32(data: bytes, offset: int) -> tuple[int, int]:
    """Returns (value, new_offset). Lidgren VarUInt: 7 bits per byte, MSB=more."""
    result = 0
    shift = 0
    while offset < len(data):
        b = data[offset]
        offset += 1
        result |= (b & 0x7F) << shift
        shift += 7
        if not (b & 0x80):
            break
    return result, offset


def read_varint32(data: bytes, offset: int) -> tuple[int, int]:
    """Zigzag-decoded signed VarInt32."""
    n, offset = read_varuint32(data, offset)
    return (n >> 1) ^ -(n & 1), offset


def read_string(data: bytes, offset: int) -> tuple[str, int]:
    """Lidgren string: VarUInt32 byte_length + UTF-8 bytes."""
    byte_len, offset = read_varuint32(data, offset)
    s = data[offset: offset + byte_len].decode("utf-8", errors="replace")
    return s, offset + byte_len


def read_uint32_le(data: bytes, offset: int) -> tuple[int, int]:
    val = struct.unpack_from("<I", data, offset)[0]
    return val, offset + 4


# ---------------------------------------------------------------------------
# StringTable state (per connection pair)
# ---------------------------------------------------------------------------
@dataclass
class ConnectionState:
    src: str
    dst: str
    string_table: dict = field(default_factory=lambda: {0: "MsgStringTableEntries"})
    pkt_count: int = 0

    def name_for_id(self, msg_id: int) -> str:
        return self.string_table.get(msg_id, f"<unknown#{msg_id}>")


# ---------------------------------------------------------------------------
# Lidgren header parser
# ---------------------------------------------------------------------------
LIDGREN_HEADER = 5  # bytes


@dataclass
class LidgrenChunk:
    msg_type: int
    seq_num: int
    is_fragment: bool
    payload_bits: int
    payload: bytes


def parse_lidgren_chunks(udp_payload: bytes) -> list[LidgrenChunk]:
    """
    A single UDP datagram may contain multiple Lidgren chunks back-to-back.
    Each chunk: [type:u8][seq_lo+frag:u8][seq_hi:u8][len_bits:u16le][payload...]
    """
    chunks = []
    offset = 0
    while offset + LIDGREN_HEADER <= len(udp_payload):
        msg_type = udp_payload[offset]
        b1 = udp_payload[offset + 1]
        b2 = udp_payload[offset + 2]
        seq_num = ((b2 & 0x7F) << 8) | b1  # lower 15 bits
        is_fragment = bool(b2 & 0x80)
        payload_bits = struct.unpack_from("<H", udp_payload, offset + 3)[0]
        payload_bytes = (payload_bits + 7) >> 3
        offset += LIDGREN_HEADER

        if offset + payload_bytes > len(udp_payload):
            # truncated – take what's available
            payload = udp_payload[offset:]
            offset = len(udp_payload)
        else:
            payload = udp_payload[offset: offset + payload_bytes]
            offset += payload_bytes

        chunks.append(LidgrenChunk(msg_type, seq_num, is_fragment, payload_bits, payload))

    return chunks


# ---------------------------------------------------------------------------
# RobustToolbox payload parser
# ---------------------------------------------------------------------------
def try_parse_string_table(payload: bytes) -> Optional[list[tuple[int, str]]]:
    """
    MsgStringTableEntries payload (ID already consumed):
      UInt32 count + for each entry: VarInt32 id + String name
    """
    if len(payload) < 4:
        return None
    try:
        count, off = read_uint32_le(payload, 0)
        if count > 10_000:
            return None
        entries = []
        for _ in range(count):
            eid, off = read_varint32(payload, off)
            name, off = read_string(payload, off)
            entries.append((eid, name))
        return entries
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Hex dump helper
# ---------------------------------------------------------------------------
def hexdump(data: bytes, indent: int = 4, width: int = 16) -> str:
    lines = []
    pad = " " * indent
    for i in range(0, len(data), width):
        chunk = data[i: i + width]
        hex_part  = " ".join(f"{b:02x}" for b in chunk)
        ascii_part = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"{pad}{i:04x}  {hex_part:<{width*3}}  {ascii_part}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Packet handler
# ---------------------------------------------------------------------------
def handle_packet(
    raw: bytes,
    src_addr: tuple,
    dst_addr: tuple,
    conn_states: dict,
    server_port: int,
    xchacha_key: Optional[bytes],
    verbose: bool,
) -> None:

    if len(raw) < LIDGREN_HEADER:
        return

    src_key = f"{src_addr[0]}:{src_addr[1]}"
    dst_key = f"{dst_addr[0]}:{dst_addr[1]}"
    pair_key = tuple(sorted([src_key, dst_key]))

    if pair_key not in conn_states:
        conn_states[pair_key] = ConnectionState(src=src_key, dst=dst_key)
    state = conn_states[pair_key]
    state.pkt_count += 1

    is_to_server = dst_addr[1] == server_port
    direction = col(C_GREEN, "C→S") if is_to_server else col(C_CYAN, "S→C")

    chunks = parse_lidgren_chunks(raw)
    ts = datetime.now().strftime("%H:%M:%S.%f")[:-3]

    for chunk in chunks:
        mt_name = NET_MSG_TYPES.get(chunk.msg_type, f"type={chunk.msg_type}")
        is_user = chunk.msg_type in USER_DATA_TYPES

        header = (
            f"{col(C_GRAY, ts)} {direction} "
            f"{col(C_BOLD, mt_name)} "
            f"seq={chunk.seq_num} "
            f"{'[FRAG] ' if chunk.is_fragment else ''}"
            f"payload={len(chunk.payload)}B"
        )

        if not is_user or len(chunk.payload) == 0:
            print(header)
            continue

        # RobustToolbox: first byte is msg_id from StringTable
        msg_id = chunk.payload[0]
        rt_payload = chunk.payload[1:]
        msg_name = state.name_for_id(msg_id)

        # Try XChaCha20-Poly1305 decrypt if key provided (after handshake).
        # Wire format: [nonce_counter:uint64-LE 8B][ciphertext+tag:N+16B]
        # The 8-byte counter is zero-padded to 24 bytes to form the XChaCha20 nonce.
        decrypted = False
        if xchacha_key and len(chunk.payload) > 0:
            try:
                from nacl.secret import SecretBox  # pynacl
                from nacl.bindings import crypto_aead_xchacha20poly1305_ietf_decrypt
                # minimum: 8 (counter) + 16 (tag) + 1 (msg_id inside plaintext) = 25 bytes
                raw = chunk.payload
                if len(raw) >= 25:
                    nonce_counter = struct.unpack_from("<Q", raw, 0)[0]
                    nonce_24 = struct.pack("<Q", nonce_counter) + b"\x00" * 16
                    ciphertext_with_tag = raw[8:]
                    plaintext = crypto_aead_xchacha20poly1305_ietf_decrypt(
                        ciphertext_with_tag, None, nonce_24, xchacha_key
                    )
                    # plaintext[0] is msg_id, rest is RT payload
                    msg_id = plaintext[0]
                    rt_payload = plaintext[1:]
                    msg_name = state.name_for_id(msg_id)
                    decrypted = True
            except Exception:
                pass

        if msg_name == "MsgStringTableEntries" and not decrypted:
            entries = try_parse_string_table(rt_payload)
            if entries:
                for eid, ename in entries:
                    state.string_table[eid] = ename
                entry_list = ", ".join(f"{eid}={ename}" for eid, ename in entries[:8])
                if len(entries) > 8:
                    entry_list += f"… (+{len(entries)-8} more)"
                print(
                    f"{header} "
                    f"| {col(C_YELLOW, msg_name)} "
                    f"({col(C_YELLOW, f'{len(entries)} entries')}: {entry_list})"
                )
                continue

        enc_note = ""
        if xchacha_key is None and msg_name.startswith("<unknown"):
            enc_note = col(C_RED, " [possibly encrypted]")
        elif xchacha_key is not None and not decrypted and msg_name.startswith("<unknown"):
            enc_note = col(C_RED, " [decrypt failed – wrong key?]")
        elif decrypted:
            enc_note = col(C_GREEN, " [decrypted]")

        print(
            f"{header} "
            f"| {col(C_YELLOW, msg_name)}{enc_note} "
            f"rt_payload={len(rt_payload)}B"
        )

        if verbose:
            print(hexdump(chunk.payload))


# ---------------------------------------------------------------------------
# Raw UDP capture using raw sockets
# ---------------------------------------------------------------------------
def capture_raw(iface: str, port: int, args) -> None:
    """
    Capture UDP packets on all interfaces using a raw socket.
    On Linux this requires root or CAP_NET_RAW.
    """
    # ETH_P_IP = 0x0800
    s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(0x0800))
    if iface:
        s.bind((iface, 0))

    conn_states: dict = {}
    xchacha_key: Optional[bytes] = None
    if args.xchacha_key:
        xchacha_key = bytes.fromhex(args.xchacha_key)
        if len(xchacha_key) != 32:
            sys.exit(f"--xchacha-key must be 64 hex chars (32 bytes), got {len(xchacha_key)}")

    print(col(C_BOLD, f"[lidgren_sniffer] listening on {iface or 'all'}, server port {port}"))
    print(col(C_GRAY, "  Ctrl+C to stop. Post-handshake packets are encrypted by default."))
    print(col(C_GRAY, "  Launch server with `net.encrypt false` to see plaintext payloads."))
    print()

    try:
        while True:
            raw_pkt, _ = s.recvfrom(65535)

            # Ethernet header: 14 bytes
            if len(raw_pkt) < 14:
                continue
            eth_type = struct.unpack_from("!H", raw_pkt, 12)[0]
            if eth_type != 0x0800:
                continue  # not IPv4

            # IP header: IHL field (lower nibble of byte 14) * 4 bytes
            ip_start = 14
            if len(raw_pkt) < ip_start + 20:
                continue
            ihl = (raw_pkt[ip_start] & 0x0F) * 4
            protocol = raw_pkt[ip_start + 9]
            if protocol != 17:  # not UDP
                continue

            src_ip = socket.inet_ntoa(raw_pkt[ip_start + 12: ip_start + 16])
            dst_ip = socket.inet_ntoa(raw_pkt[ip_start + 16: ip_start + 20])

            # UDP header: 8 bytes
            udp_start = ip_start + ihl
            if len(raw_pkt) < udp_start + 8:
                continue
            src_port = struct.unpack_from("!H", raw_pkt, udp_start)[0]
            dst_port = struct.unpack_from("!H", raw_pkt, udp_start + 2)[0]

            if src_port != port and dst_port != port:
                continue  # not our SS14 traffic

            udp_payload = raw_pkt[udp_start + 8:]
            if not udp_payload:
                continue

            handle_packet(
                udp_payload,
                (src_ip, src_port),
                (dst_ip, dst_port),
                conn_states,
                server_port=port,
                xchacha_key=xchacha_key,
                verbose=args.verbose,
            )

    except KeyboardInterrupt:
        total = sum(s.pkt_count for s in conn_states.values())
        print(f"\n[done] captured {total} packets across {len(conn_states)} connections")


# ---------------------------------------------------------------------------
# Pcap replay mode – parse a .pcap file instead of live capture
# ---------------------------------------------------------------------------
def replay_pcap(path: str, port: int, args) -> None:
    """
    Minimal pcap parser (no scapy needed).
    Supports pcap (little-endian) with linktype LINKTYPE_ETHERNET (1).
    """
    with open(path, "rb") as f:
        magic = struct.unpack("<I", f.read(4))[0]
        if magic not in (0xA1B2C3D4, 0xA1B23C4D):
            sys.exit("Not a pcap file (check magic bytes)")
        _ver_maj, _ver_min, _thiszone, _sigfigs, snaplen, linktype = struct.unpack("<HHiIII", f.read(20))
        if linktype not in (1, 101):  # Ethernet or raw IP
            sys.exit(f"Unsupported linktype {linktype}; only Ethernet(1) and RawIP(101) supported")

        conn_states: dict = {}
        xchacha_key: Optional[bytes] = None
        if args.xchacha_key:
            xchacha_key = bytes.fromhex(args.xchacha_key)
            if len(xchacha_key) != 32:
                sys.exit(f"--xchacha-key must be 64 hex chars (32 bytes), got {len(xchacha_key)}")

        print(col(C_BOLD, f"[lidgren_sniffer] replaying {path}, server port {port}"))
        count = 0

        while True:
            hdr = f.read(16)
            if len(hdr) < 16:
                break
            ts_sec, ts_usec, incl_len, orig_len = struct.unpack("<IIII", hdr)
            frame = f.read(incl_len)
            if len(frame) < incl_len:
                break

            if linktype == 1:
                # Ethernet
                if len(frame) < 14:
                    continue
                eth_type = struct.unpack_from("!H", frame, 12)[0]
                if eth_type != 0x0800:
                    continue
                ip_start = 14
            else:
                ip_start = 0  # raw IP

            if len(frame) < ip_start + 20:
                continue
            ihl = (frame[ip_start] & 0x0F) * 4
            if frame[ip_start + 9] != 17:
                continue  # not UDP

            src_ip = socket.inet_ntoa(frame[ip_start + 12: ip_start + 16])
            dst_ip = socket.inet_ntoa(frame[ip_start + 16: ip_start + 20])

            udp_start = ip_start + ihl
            if len(frame) < udp_start + 8:
                continue

            src_port = struct.unpack_from("!H", frame, udp_start)[0]
            dst_port = struct.unpack_from("!H", frame, udp_start + 2)[0]

            if src_port != port and dst_port != port:
                continue

            udp_payload = frame[udp_start + 8:]
            if not udp_payload:
                continue

            handle_packet(
                udp_payload,
                (src_ip, src_port),
                (dst_ip, dst_port),
                conn_states,
                server_port=port,
                xchacha_key=xchacha_key,
                verbose=args.verbose,
            )
            count += 1

        total = sum(s.pkt_count for s in conn_states.values())
        print(f"\n[done] {count} UDP frames replayed, {total} lidgren packets parsed")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    global USE_COLOR
    parser = argparse.ArgumentParser(
        description="Lidgren/RobustToolbox UDP sniffer for Space Station 14",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              # Live capture (needs root / CAP_NET_RAW):
              sudo python3 lidgren_udp_sniffer.py --port 1212 --iface lo

              # Replay a pcap captured with tcpdump:
              tcpdump -i lo -w ss14.pcap udp port 1212
              python3 lidgren_udp_sniffer.py --pcap ss14.pcap --port 1212

              # Show hex dumps of every payload:
              sudo python3 lidgren_udp_sniffer.py --port 1212 --verbose

              # Decrypt post-handshake traffic (XChaCha20-Poly1305 key as hex, 64 chars = 32 bytes):
              # Extract the key via source patch in NetManager.ClientConnect.cs (see file docstring)
              sudo python3 lidgren_udp_sniffer.py --port 1212 --xchacha-key AABBCC...{60 more hex chars}
        """),
    )
    parser.add_argument("--port",         type=int, default=1212, help="SS14 server UDP port (default 1212)")
    parser.add_argument("--iface",        default="",             help="Network interface for live capture")
    parser.add_argument("--pcap",         default="",             help="Replay a .pcap file instead of live capture")
    parser.add_argument("--xchacha-key",  default="",             dest="xchacha_key",
                        help="XChaCha20-Poly1305 session key (64 hex chars = 32 bytes) for decrypting post-handshake packets")
    parser.add_argument("--verbose", "-v", action="store_true", help="Print hex dump of each payload")
    parser.add_argument("--no-color", action="store_true",  help="Disable ANSI colour output")
    args = parser.parse_args()

    if args.no_color:
        USE_COLOR = False

    if args.pcap:
        replay_pcap(args.pcap, args.port, args)
    else:
        if sys.platform != "linux":
            sys.exit("Live capture uses AF_PACKET; Linux only. Use --pcap for other platforms.")
        capture_raw(args.iface, args.port, args)


if __name__ == "__main__":
    main()
